import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// pages/_app.js
import { ChakraProvider } from "@chakra-ui/react";
import Index from "./index";

import React, { useState, useEffect } from "react";

//Login Page
import Login from "../components/login/login";

// //Farm
const FarmHeader = React.lazy(() => import("../components/farm/menu/header"));
const Farm = React.lazy(() => import("../components/farm/dashboard/farm"));

// //Processor
const ProcessorHeader = React.lazy(() =>
  import("../components/processor/menu/header")
);
const Processor = React.lazy(() =>
  import("../components/processor/dashboard/processor")
);

//Exportir
const ExportirHeader = React.lazy(() =>
  import("../components/exportir/menu/header")
);

function MyApp({ Component, pageProps }) {
  const [user, setUser] = useState([]);

  useEffect(() => {
    const users = localStorage.getItem("user");
    if (users) {
      setUser(users);
    } else {
      setUser(null);
    }
  }, []);

  const onLoggedIn = (role) => {
    localStorage.setItem("user", role);
    if(role == 'Farm') {
      window.open('/farm', "_self");
    } else if(role == 'Processor'){
      window.open('/processor', "_self");
    } else if(role == 'Exportir'){
      window.open('/exportir', "_self");
    } else {
      window.open("/login", "_self");
    }
  };

  const onLogoutClicked = () => {
    localStorage.removeItem("user");
    window.open("/login", "_self");
  };
  return (
    <ChakraProvider>
      <Head>
        <title>Kopi Ketjil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo/favicon-kopiketjil.png" />
      </Head>
      {(() => {
        if (!user) {
          return (
            <>
              {/* <Login onLoggedIn={onLoggedIn} /> */}
              <Component {...pageProps} />
            </>
          );
        } else if (user == "Farm") {
          return (
            <>
              <FarmHeader onLogoutClicked={onLogoutClicked} />
              {/* <Farm /> */}
              <Component {...pageProps} />
            </>
          );
        } else if (user == "Processor") {
          return (
            <>
              <ProcessorHeader onLogoutClicked={onLogoutClicked} />
              {/* <Processor /> */}
              <Component {...pageProps} />
            </>
          );
        } else if (user == "Exportir") {
          return (
            <>
              <ExportirHeader onLogoutClicked={onLogoutClicked} />
              <Component {...pageProps} />
            </>
          );
        }
      })()}
    </ChakraProvider>
  );
}

export default MyApp;
